const translations = {
  17: {
    story:
      'We launched the Chinese Characters 5K NFT project on IC, a collection of 5,000 commonly used Chinese characters that are simple, atmospheric and unique.\nOur vision is to spread and promote Chinese culture: to let the world know the story of each Chinese character, the essence of each group of words, and the underlying meaning of each verse.\nChinese characters will write poems in web 3.0, which is a great and meaningful thing',
    rewards:
      "I. Chinese character crowdfunding: We will launch a fundraising campaign for 5000 Chinese characters NFT at 0.1 ICP.\nII. English Airdrop: We will airdrop 26 English letters NFT in a-z after the project is launched. \nThird, word casting: Word NFT holders can be used to combine casting words NFT and casting statements NFT. these NFT will be displayed in web3.0's cooperative application platform and get revenue, applications include blog category, game category, meta-universe category, etc. \n1、 Word formation \n2、 Word/phrase making \nFourth, text stories: NFT holders can compile background stories and store them in NFT's built-in application [dictionary], which will remain in web3.0 forever. \nV. Poems and songs: In the future, we strive to cooperate with the Chinese Education Bureau and other units to cast traditional classic poems and songs, which will be in the form of an auction.\n\n---------------------------------------------------\n\nAs decided by the community vote, the crowdfunding price is updated to 0.5 ICP, and the crowdfunding fund is 2500 ICP about 180,000 RMB.\n\nCrowdfunding funds will be used for team recruitment, project development and community development. The funds will be deposited in the foundation account and will be open and transparent to the community. After the project is established and the results are accepted in stages, the project team will launch the project bonus application, and the funds will be released by the foundation after the community votes.\n\nThe first version will be developed and delivered online within two months.\n\n---------------------------------------------------\n\nBuyback Program\n\nIn order to promote the development of Chinese characters NFT and achieve the small goal of one word for a thousand dollars. The foundation will recover from the secondary market with a buyback price\n\nBuyback Price = Crowdfunding Price x 0.8 + 0.01x (Current Date - Crowdfunding Success Date)\n \nFor example, 30 days after the completion of the crowdfunding, the buyback price is 0.7 ICP (0.5x0.8 + 0.01x30)",
  },
}

export default translations
